//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminPortalEntities : DbContext
    {
        public AdminPortalEntities()
            : base("name=AdminPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<LookupCodeMaster> LookupCodeMasters { get; set; }
        public virtual DbSet<LookupTypeMaster> LookupTypeMasters { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<RecruitmentClient> RecruitmentClients { get; set; }
        public virtual DbSet<TimeSheetSummary> TimeSheetSummaries { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<LOA> LOAs { get; set; }
        public virtual DbSet<Recruitment> Recruitments { get; set; }
        public virtual DbSet<RecruitmentDocument> RecruitmentDocuments { get; set; }
        public virtual DbSet<RecruitmentClientDocument> RecruitmentClientDocuments { get; set; }
        public virtual DbSet<SupportMaster> SupportMasters { get; set; }
        public virtual DbSet<SupportAttachment> SupportAttachments { get; set; }
        public virtual DbSet<ExpenseMaster> ExpenseMasters { get; set; }
        public virtual DbSet<ExpenseAttachment> ExpenseAttachments { get; set; }
        public virtual DbSet<ExpenseSummary> ExpenseSummaries { get; set; }
        public virtual DbSet<TimeSheetsMaster> TimeSheetsMasters { get; set; }
    }
}
