//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseSummary
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public decimal Miles { get; set; }
        public decimal MilesMultiplicationFactor { get; set; }
        public decimal MilesDriven { get; set; }
        public decimal Transport { get; set; }
        public decimal Lodging { get; set; }
        public decimal Meals { get; set; }
        public decimal Phone { get; set; }
        public decimal Other { get; set; }
        public decimal Total { get; set; }
    
        public virtual ExpenseMaster ExpenseMaster { get; set; }
    }
}
