//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOA
    {
        public int LoaId { get; set; }
        public string LoaCode { get; set; }
        public string UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int LookupTimeOfDay { get; set; }
        public string OtherTimeOfDay { get; set; }
        public int LookupTypeOfLeave { get; set; }
        public string OtherTypeOfLeave { get; set; }
        public string ReasonForLeave { get; set; }
        public int LookupLoaStatus { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster1 { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster2 { get; set; }
    }
}
