//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int LookupCategory { get; set; }
        public int LookupProductType { get; set; }
        public string MakeModel { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Version { get; set; }
        public string AssignTo { get; set; }
        public string Description { get; set; }
        public Nullable<int> LookupStatus { get; set; }
        public Nullable<int> LookupPlatform { get; set; }
        public string Url { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ActivationKey { get; set; }
        public string ProductCompany { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OtherProductType { get; set; }
        public string MembershipId { get; set; }
        public string GrantNumber { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string AssignToHardware { get; set; }
        public string Location { get; set; }
        public string OtherAssignedUser { get; set; }
    
        public virtual LookupCodeMaster Category { get; set; }
        public virtual LookupCodeMaster Platform { get; set; }
        public virtual LookupCodeMaster Status { get; set; }
        public virtual LookupCodeMaster ProductType { get; set; }
        public virtual AspNetUser AssignedUser { get; set; }
    }
}
