//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportMaster()
        {
            this.SupportAttachments = new HashSet<SupportAttachment>();
        }
    
        public int SupportId { get; set; }
        public string SupportCode { get; set; }
        public string UserId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public int LookupIssuePriority { get; set; }
        public int LookupIssueStatus { get; set; }
        public int LookupIssueType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string AssignTo { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> FixedTime { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public string UserComments { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster1 { get; set; }
        public virtual LookupCodeMaster LookupCodeMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportAttachment> SupportAttachments { get; set; }
    }
}
