//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetSummary
    {
        public int ID { get; set; }
        public int TimeSheetID { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public decimal Day1Hours { get; set; }
        public decimal Day2Hours { get; set; }
        public decimal Day3Hours { get; set; }
        public decimal Day4Hours { get; set; }
        public decimal Day5Hours { get; set; }
        public decimal Day6Hours { get; set; }
        public decimal Day7Hours { get; set; }
    
        public virtual TimeSheetsMaster TimeSheetsMaster { get; set; }
    }
}
